import {
  mdiDotsVertical,
  mdiDrag,
  mdiPencil,
  mdiPlus,
  mdiListBoxOutline,
  mdiDelete,
  mdiContentCopy,
  mdiContentCut,
  mdiClose,
  mdiChevronRight,
  mdiChevronLeft,
  mdiChevronUp,
  mdiChevronDown,
  mdiCodeJson,
  mdiThemeLightDark,
  mdiRestart,
  mdiGrid,
  mdiEye,
  mdiCog,
  mdiCursorMove,
  mdiCloseCircle,
  mdiCheckCircle,
  mdiDotsHexagon,
  mdiCodeBracesBox,
  mdiArrowUp,
  mdiArrowDown,
  mdiMinus,
  mdiDotsHorizontal,
} from '@mdi/js';

export const ICON = {
  CLOSE: mdiClose,
  CODE_BRACES: mdiCodeBracesBox,
  CONTENT_COPY: mdiContentCopy,
  CONTENT_CUT: mdiContentCut,
  DELETE: mdiDelete,
  DOTS_VERTICAL: mdiDotsVertical,
  DRAG: mdiDrag,
  LIST_BOX_OUTLINE: mdiListBoxOutline,
  PENCIL: mdiPencil,
  PLUS: mdiPlus,
  CHEVRON_RIGHT: mdiChevronRight,
  CHEVRON_LEFT: mdiChevronLeft,
  CHEVRON_DOWN: mdiChevronDown,
  CHEVRON_UP: mdiChevronUp,
  CODE_JSON: mdiCodeJson,
  THEME_LIGHT_DARK: mdiThemeLightDark,
  RESTART: mdiRestart,
  GRID: mdiGrid,
  EYE: mdiEye,
  COG: mdiCog,
  CURSOR_MOVE: mdiCursorMove,
  CLOSE_CIRCLE: mdiCloseCircle,
  CHECK_CIRCLE: mdiCheckCircle,
  DOTS_HEXAGON: mdiDotsHexagon,
  ARROW_UP: mdiArrowUp,
  ARROW_DOWN: mdiArrowDown,
  MINUS: mdiMinus,
  DOTS_HORIZONTAL: mdiDotsHorizontal,
};
